create table doctor (
id bigint generated by default as identity (start with 1),
name varchar(255) not null,
surname varchar(255) not null,
patronymic varchar(255) not null,
specialization varchar(255) not null,
primary key (id));

create table patient (
id bigint generated by default as identity (start with 1),
name varchar(255) not null,
surname varchar(255) not null,
patronymic varchar(255) not null,
phone varchar(255) not null,
primary key (id));

create table recipe (
id bigint generated by default as identity (start with 1),
description varchar(255) not null,
create_date date not null,
expiry_date date not null,
priority varchar(255) not null,
doctor_id bigint not null references doctor,
patient_id bigint not null references patient,
primary key (id));
